# Generated by Django 5.2.7 on 2025-10-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
