# Generated by Django 5.2.7 on 2025-10-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_visit_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Wizyta', 'verbose_name_plural': 'Wizyty'},
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono')], default='pending', max_length=10, verbose_name='Status wizyty'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['date'], name='main_app_vi_date_fe6c9b_idx'),
        ),
    ]
