# Generated by Django 5.2.7 on 2025-10-31 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_visit_options_visit_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bol_przy_nagryzaniu', models.BooleanField(default=0)),
                ('bol_na_zimno', models.BooleanField(default=0)),
                ('obrzek_policzka', models.BooleanField(default=0)),
                ('wysoka_temperatura', models.BooleanField(default=0)),
                ('zab_sie_rusza', models.BooleanField(default=0)),
                ('zab_zciemnial', models.BooleanField(default=0)),
                ('reakcja_na_slodkie', models.BooleanField(default=0)),
                ('bol_samoistny', models.BooleanField(default=0)),
                ('silny_bol_podczas_picia_goracych_napojow', models.BooleanField(default=0)),
                ('bol_dziasla', models.BooleanField(default=0)),
                ('nadwrazliwy_zab', models.BooleanField(default=0)),
                ('bol_na_slodkie', models.BooleanField(default=0)),
                ('reakcja_na_zimno', models.BooleanField(default=0)),
                ('bol_na_cieplo', models.BooleanField(default=0)),
                ('bol_zeba_od_kilku_dni', models.BooleanField(default=0)),
                ('krwawienie_z_dziasel', models.BooleanField(default=0)),
                ('silne_bole_samoistne_ktore_lagodzi_zimny_napoj', models.BooleanField(default=0)),
                ('reakcja_na_cieplo', models.BooleanField(default=0)),
                ('brzydki_zapach_z_ust', models.BooleanField(default=0)),
                ('krwawienie_z_dziasel_przy_myciu_zebow', models.BooleanField(default=0)),
                ('wrazliwosc_na_zimno', models.BooleanField(default=0)),
                ('predicted_diagnosis', models.CharField(max_length=255)),
                ('is_new', models.BooleanField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='main_app.diagnosismodel', verbose_name='Diagnoza'),
        ),
    ]
