# Generated by Django 5.2.7 on 2025-11-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_diagnosismodel_visit_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='visit',
            name='predicted_diagnosis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicted_visits', to='main_app.diagnosismodel', verbose_name='Diagnoza_Ai'),
        ),
    ]
