# Generated by Django 5.2.7 on 2025-11-06 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_customuser_is_guest_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthday',
        ),
    ]
