# Generated by Django 5.2.7 on 2025-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_customuser_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono'), ('canceled', 'Anulowano')], default='pending', max_length=10, verbose_name='Status wizyty'),
        ),
    ]
