# Generated by Django 5.2.7 on 2025-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnoza'),
        ),
        migrations.AddField(
            model_name='visit',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Notatka'),
        ),
    ]
