# Generated by Django 5.2.7 on 2025-12-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_visit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_same',
            field=models.BooleanField(default=0),
        ),
    ]
