# Generated by Django 5.2.7 on 2025-12-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_visit_is_same'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('accepted', 'Zaakceptowano'), ('rejected', 'Odrzucono'), ('canceled', 'Anulowano'), ('presence', 'Obecność'), ('absent', 'Nieobecność')], default='pending', max_length=10, verbose_name='Status wizyty'),
        ),
    ]
