# Generated by Django 5.2.7 on 2025-12-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_algorithm', models.CharField(choices=[('nn', 'Neural Network'), ('rf', 'Random Forest')], default='nn', max_length=2, verbose_name='Algorytm diagnozy')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ustawienia systemu',
                'verbose_name_plural': 'Ustawienia systemu',
            },
        ),
    ]
