# Generated by Django 5.2.7 on 2025-12-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_systemsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosismodel',
            name='is_new',
        ),
        migrations.AddField(
            model_name='diagnosismodel',
            name='is_new_nn',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosismodel',
            name='is_new_rf',
            field=models.BooleanField(default=0),
        ),
    ]
