# Generated by Django 5.2.7 on 2025-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_diagnosismodel_is_new_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='is_correct',
            field=models.BooleanField(default=0),
        ),
    ]
