# Generated by Django 5.2.7 on 2025-12-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_diagnosismodel_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosismodel',
            name='doctor_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
